version: '3.4'

services:
  play-catalog-service:
    image: play.catalog.service
    hostname: play-catalog-service
    container_name: play-catalog-service
    build:
      context: .
      dockerfile: services/catalog/src/Play.Catalog.Service/Dockerfile
    environment:
      - APP_ID=play-catalog-service
      - APP_PORT=5100
      - DAPR_HTTP_PORT=3100
      - DAPR_GRPC_PORT=4001
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5100:80"
      - "3100:3100"
    depends_on:
      - postgres
      - rabbitmq
      - placement
    networks:
      - play-economy
  play-catalog-service-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd",
               "-app-id", "play-catalog-service",
               "-app-port", "5100",
               "-dapr-http-port", "3100",
               "-placement-host-address", "placement:50006",
               "-dapr-grpc-port", "4001",
               "-resources-path", "/components",
               "-log-level","debug" ]
    volumes:
      - "./services/catalog/src/Play.Catalog.Service/.components:/components"
    depends_on:
      - play-catalog-service
    network_mode: "service:play-catalog-service"

  play-customer-service:
    image: play.customer.service
    build:
      context: .
      dockerfile: services/customer/src/Play.Customer.Service/Dockerfile
    environment:
      - APP_ID=play-customer-service
      - APP_PORT=5300
      - DAPR_HTTP_PORT=3300
      - DAPR_GRPC_PORT=4003
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Local
    ports:
      - "5300:80"
      - "3300:3300"
    depends_on:
      - postgres
      - rabbitmq
      - placement
    networks:
      - play-economy
  play-customer-service-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd",
               "-app-id", "play-customer-service",
               "-app-port", "5300",
               "-dapr-http-port", "3300",
               "-placement-host-address", "placement:50006",
               "-dapr-grpc-port", "4003",
               "-resources-path", "/components",
               "-log-level","debug" ]
    volumes:
      - "./services/customer/src/Play.Customer.Service/.components:/components"
    depends_on:
      - play-customer-service
    network_mode: "service:play-customer-service"
  
  play-inventory-service:
    image: play.inventory.service
    build:
      context: .
      dockerfile: services/inventory/src/Play.Inventory.Service/Dockerfile
    environment:
      - APP_ID=play-inventory-service
      - APP_PORT=5200
      - DAPR_HTTP_PORT=3200
      - DAPR_GRPC_PORT=4002
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5200:80"
      - "3200:3200"
    depends_on:
      - postgres
      - rabbitmq
      - placement
    networks:
      - play-economy
  play-inventory-service-dapr:
    image: "daprio/daprd:latest"
    command: [ "./daprd",
               "-app-id", "play-inventory-service",
               "-app-port", "5200",
               "-dapr-http-port", "3200",
               "-placement-host-address", "placement:50006",
               "-dapr-grpc-port", "4002",
               "-resources-path", "/components",
               "-log-level","debug" ]
    volumes:
      - "./services/inventory/src/Play.Inventory.Service/.components:/components"
    depends_on:
      - play-inventory-service
    network_mode: "service:play-inventory-service"

  placement:
    image: "daprio/dapr"
    command: [ "./placement", "-port", "50006" ]
    ports:
      - "50006:50006"
    networks:
      - play-economy

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - play-economy

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - play-economy

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - play-economy
    depends_on:
      - postgres

networks:
  play-economy:

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  rabbitmq_data:
    driver: local