apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: play-catalog-state-store
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "host=127.0.0.1 user=admin password=admin port=5432 connect_timeout=10 database=Play.Catalog"
  - name: actorStateStore
    value: "true"
  - name: keyPrefix
    value: "none"
  - name: actorStateStore
    value: "true"