apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: play-inventory-service-pubsub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      value: "amqp://guest:guest@127.0.0.1:5672"
    - name: consumerID
      value: play-inventory-service
    - name: deletedWhenUnused
      value: false
    - name: deliveryMode
      value: 2
    - name: requeueInFailure
      value: false
    - name: prefetchCount
      value: 1
    - name: reconnectWait
      value: 1
    - name: concurrencyMode
      value: parallel
    - name: publisherConfirm
      value: false
    - name: enableDeadLetter # Optional enable dead Letter or not
      value: true
    - name: maxLen # Optional max message count in a queue
      value: 3000
    - name: maxLenBytes # Optional maximum length in bytes of a queue.
      value: 10485760
    - name: exchangeKind
      value: fanout