apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: play-inventory-state-store
spec:
  type: state.postgresql
  version: v1
  metadata:
    - name: connectionString
      value: "host=localhost user=admin password=admin port=5432 connect_timeout=10 database=Play.Inventory"
    - name: actorStateStore
      value: "true"
    - name: keyPrefix
      value: "none"